#!/bin/bash
#Begin bash by AmirKalan
c1() {
mkdir $HOME/.conky/QPL
mv Check_Network.lua ~/.conky/QPL
mv Project ~/.conky/QPL
mv Projectv2 ~/.conky/QPL
mv Projectv3 ~/.conky/QPL
mv source.txt ~/.conky/QPL
mv ./fonts/monofur.ttf ~/.conky/fonts
mv ./fonts/ADELE.ttf ~/.conky/fonts
mv ./fonts/Feena* ~/.conky/fonts
mv ./fonts ~/.conky/QPL
mv .git ~/.conky/QPL
cd $HOME/.conky/QPL
mv Project .Project
mv Projectv2  .Projectv2
mv Projectv3 Projectv3
}
function config(){
    echo -e "\e[107m                              Configing....                          \e[00;37;40m"
if [ -d "$HOME/.conky" ];then
c1
sleep 2
echo -e "\e[1m\e[97m==> QPL Conky successfully installed ! "
else
echo -e "\e[1m\e[97m==> Installing Conky Manager ! "
wget --no-check-certificate 'https://github.com/teejee2008/conky-manager/releases/download/v2.4/conky-manager-v2.4-amd64.run' 
chmod +x conky-manager-v2.4-amd64.run
sudo ./conky-manager-v2.4-amd64.run
    echo -e "\e[107m                              Configing....                          \e[00;37;40m"
conky-manager
c1
sleep 2
echo -e "\e[1m\e[97m==> QPL Conky successfully installed ! "
fi
}
function update(){
    echo -e "\e[107m                              Updateing....                          \e[00;37;40m"
if [ -d "$HOME/.conky/QPL" ];then
cd $HOME/.conky/QPL
git pull
sleep 2 
lua Check_Network.lua
else
echo -e "\e[1m\e[97m==> Config Error ! "
exit 0
fi
}
function run(){
    echo -e "\e[107m                              Launching....                          \e[00;37;40m"
if [ -d "$HOME/.conky/QPL" ];then
cd $HOME/.conky/QPL
lua Check_Network.lua 
conky-manager
else
echo -e "\e[1m\e[97m==> Config Error ! "

exit 0
fi
}
case $1 in
config)
config
exit;;
update)
update
exit;;
start)
run
exit;;
esac
exit 0

